### Site Settings ###
title               : Balaji Seetharaman
description         : >- 
                      I turn tea :tea: into code,     
                      Want to discuss ?? Always up for Networking, Data Science, Deep Learning, Quantum Computing, 
                      Teaching methodologies, Volunteering & Tamil Literature!!! 
#baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : bala-ceg/bala-ceg.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : bala-ceg/portfolYOU


### Plugins ###
plugins:
  - jemoji

encoding: UTF-8

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/testblog.md
  - pages/status.md
  - pages/contact.md

  #  - pages/contact.html

### Author Info ###
author:
  name              : Balaji Seetharaman
  image             : ./assets/Cover.jpg
# behance           : your_username
# dribbble          : your_username
  email             : balaji_ceg@outlook.com  
# facebook          : your_username
  github            : bala-ceg
# gitlab            : your_username
# instagram         : udaygirish
# kaggle            : udaygirish
  linkedin          : balaji-seetharaman-a90961100
  medium            : bala_ceg
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter          : UdayGirishM
# vimeo             : your_username
# youtube           : your_channel_name
# quora             : Uday-Girish-Maradana
# resume            : Uday_Girish_CV.pdf
  

### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Disqus ###                        
disqus:        # Your website Shortname on disqus
  shortname: https-bala-ceg-github-io  

### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: 


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                  # Set to true to enable disqus comments
  - scope:
      path: ""
      type: "skills"
    values:
      comments: false 

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
